apiVersion: v1
kind: Pod
metadata:
  name: weather-es
  labels:
    app: weather-elasticsearch
spec:
  # initContainers:
  #   - name: fix-permissions
  #     image: busybox
  #     command: ['sh', 'chown -R 1000:1000 /usr/share/elasticsearch/data']
  #     securityContext:
  #       privileged: true
  #     volumeMounts:
  #       - name: storage
  #         mountPath: /usr/share/elasticsearch/data
  containers:
  - image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    name: elasticsearch
    env:
    - name: node.name
      value: es01
    - name: discovery.type
      value: single-node
    - name: bootstrap.memory_lock
      value: "true"
    - name: ES_JAVA_OPTS
      value: "-Xms512m -Xmx512m"
    volumeMounts:
    - name: storage
#      mountPath: /usr/share/elasticsearch/data
      mountPath: /data
      readOnly: false
    ports:
    - containerPort: 9200
      name: http
      protocol: TCP
    - containerPort: 9300
      name: transport
      protocol: TCP
  volumes:
  - name: storage
    persistentVolumeClaim:
      claimName: weather-pvc
