apiVersion: v1
kind: PersistentVolume
metadata:
  name: weather-pv
spec:
  capacity:
    storage: 50Gi
  accessModes: 
  - ReadWriteOnce
  claimRef:
    namespace: default
    name: weather-pvc
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk: 
    pdName: elasticdisk
    fsType: ext4
