apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weather-pvc
spec:
  resources:
    requests:
      storage: 50Gi 
  accessModes:
    - ReadWriteOnce
#  storageClassName: "standard"
  storageClassName: ""
